# .github/release.yml

changelog:
  categories:
    - title: New Features 🚀
      labels:
        - feature
        - enhancement
    
    - title: Bug Fixes 🐛
      labels:
        - bug
    
    - title: Documentation 📚
      labels:
        - documentation
        - website

    - title: Testing 🧪
      labels:
        - tests

    - title: Dependency
      labels:
        - dependencies
    
    - title: Other Changes
      labels:
        - "*"
