name: Release (CI/CD)

on:
  release:
    types: [published]

jobs:
  release-nature:
    needs: build
    
    runs-on: ubuntu-latest

    steps:
      - name: Check release type
        run: |
          if [ "${{ github.event.release.prerelease }}" == "false" ]; then
            echo "Stable Release."
          else
            echo "Prerelease Release"
          fi
    
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven

    - name: Run Tests
      run: |
        mvn test
        
    - name: Build Code
      run: |
        mvn package
    
    - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-application-artifact
          path: dist/*.jar
          retention-days: 1
    
    - name: Build project
        run: |
          zip --junk-paths my-artifact.zip dist/*.jar README.md LICENSE.txt

    - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: passcodes-java-${{ github.event.release.name }}.zip
          asset_path: ./my-artifact.zip
          asset_content_type: application/zip
